import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import EmployeeTable from '../components/EmployeeTable'
import Navbar from '../components/Navbar'
import Table from '../components/Table'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100 w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-2xl font-bold text-center py-10">Employee Management System</h1>
      <Table />
    </div>
  )
}

export default Home
